/*
Feeds represents all data accessed through a given configuration.
A feed can have various locations which may have all the same or different ownership.
*/
CREATE TABLE IF NOT EXISTS feeds (
    feed_id integer primary key generated always as identity,
    configuration_path text not null,
    configuration jsonb
);

/*
measurands is used to store all data type units that are available to store
*/
CREATE TABLE IF NOT EXISTS measurands  (
    measurand_id integer primary key generated always as identity,
    measurand text not null,
    unit text not null,
    UNIQUE (measurand, unit)
);

/*
Stations is used to describe the grouping of all sensor platforms
that are colocated. This could be on a tower, a mobile platform, etc.
*/
CREATE TABLE IF NOT EXISTS stations  (
    station_id integer primary key generated always as identity,
    station_name text unique not null,
    feed_id integer references feeds(feed_id),
    geog geography,
    mobile boolean default false,
    city text,
    country text,
    station_metadata jsonb
);

/*
A group of sensors that are all part of a single platform.
ie a Purlple Monitor platform may have two monitors as part of the system.
*/
CREATE TABLE IF NOT EXISTS sensor_platforms  (
    sensor_platform_id integer primary key generated always as identity,
    station_id integer references stations(station_id),
    organization text,
    project text,
    organization_type text,
    attribution jsonb,
    license text,
    sensor_platform_metadata jsonb
);

/*
A given configuration of an individual sensor. If a configuration changes, records for the same sensor are still tied together by the sensor_id so it is possible to see the different versions of configuration for any sensor.
*/
CREATE TABLE IF NOT EXISTS sensor_configurations (
    sensor_configuration_id integer primary key generated always as identity,
    sensor_id integer generated by default as identity,
    sensor_platform_id integer not null references sensor_platforms(sensor_platform_id),
    measurand_id integer not null references measurands(measurand_id),
    averaging_period interval,
    sensor_approx_cost real,
    frequency interval,
    sensor_metadata jsonb
);

/*
The actual measurement tables. We keep these as light as possible including separating stationary (where the location is stored as part of the station) and mobile (which require an additional location stored for each reading) since this is the table which can have billions of records.
*/
CREATE TABLE measurements_stationary (
    sensor_configuration_id integer references sensor_configurations(sensor_configuration_id) not null,
    ts timestamptz not null,
    value float not null,
    UNIQUE (sensor_configuration_id, ts)
);

CREATE TABLE measurements_mobile (
    sensor_configuration_id integer references sensor_configurations(sensor_configuration_id) not null,
    ts timestamptz not null,
    value float not null,
    geog geography not  null,
    UNIQUE (sensor_configuration_id, ts)
);
